### ISSUE TITLE
[BUG] panic: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by Zehir** [automuteus/automuteus#518]
**Describe the bug**
I updated my selfhosted instance from version 7.4.0 to 8.3.3 and now when I run the stack I get this errors from the `automuteus/automuteus` container;

```bash
2023/11/18 12:19:15 8.3.3-f0971d9
2023/11/18 12:19:15 No NUM_SHARDS specified; defaulting to 1
2023/11/18 12:19:15 No SHARDS specified, defaulting to 0
2023/11/18 12:19:15 [Locale] Loaded language: de - Englisch
2023/11/18 12:19:15 [Locale] Loaded language: en - English
2023/11/18 12:19:15 [Locale] Loaded language: es - Inglés
2023/11/18 12:19:15 [Locale] Loaded language: fr - Anglais
2023/11/18 12:19:15 [Locale] Loaded language: it - Inglese
2023/11/18 12:19:15 [Locale] Loaded language: ja - 日本語
2023/11/18 12:19:15 [Locale] Loaded language: no - Engelsk
2023/11/18 12:19:15 [Locale] Loaded language: pl - Angielski
2023/11/18 12:19:15 [Locale] Loaded language: pt - Portuguese-Brazil
2023/11/18 12:19:15 [Locale] Loaded language: ro - Română
2023/11/18 12:19:15 [Locale] Loaded language: ru - Russian
2023/11/18 12:19:15 [Locale] Loaded language: sv - Engelska
2023/11/18 12:19:15 [Locale] Loaded language: uk - Українська
2023/11/18 12:19:15 [Locale] Loaded language: zh - Distr.
panic: unaligned 64-bit atomic operation
goroutine 1 [running]:
runtime/internal/atomic.panicUnaligned()
	/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0x3d3a044)
	/usr/local/go/src/runtime/internal/atomic/atomic_arm.s:280 +0x14
github.com/jackc/pgx/v4/pgxpool.(*Pool).Stat(0x3d3a000)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.0/pgxpool/pool.go:577 +0x38
github.com/jackc/pgx/v4/pgxpool.(*Pool).checkMinConns(0x3d3a000)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.0/pgxpool/pool.go:490 +0x1c
github.com/jackc/pgx/v4/pgxpool.ConnectConfig({0xc9c350, 0x302a0d8}, 0x33d6bc0)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.0/pgxpool/pool.go:266 +0x34c
github.com/jackc/pgx/v4/pgxpool.Connect({0xc9c350, 0x302a0d8}, {0x3cbdab0, 0x70})
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.0/pgxpool/pool.go:178 +0x60
github.com/automuteus/automuteus/v8/pkg/storage.(*PsqlInterface).Init(0x3eaab70, {0x3cbdab0, 0x70})
	/src/pkg/storage/postgres.go:45 +0x38
main.discordMainWrapper()
	/src/main.go:160 +0xa98
main.main()
	/src/main.go:52 +0x9c
```

**To Reproduce**
I used a raspberry pi 4 8GB RAM with every packages updated to current version.
I copy the latest version of the https://github.com/automuteus/deploy/blob/main/docker-compose.yml inside portainer and import all env from https://github.com/automuteus/deploy/blob/main/sample.env with the adition of the tokens and passwords from the previous version.
```env
AUTOMUTEUS_TAG=8.3.3
GALACTUS_TAG=4.0.0
```

**Expected behavior**
I expect the container to start

**Screenshots**
Nothing to see

**Version of bot & capture**
 - Bot: 8.3.3
 - Capture: Not yet downloaded

**Additional Information**
```bash
root@raspberrypi-nes:~# uname -a
Linux raspberrypi-nes 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

root@raspberrypi-nes:~# docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED          STATUS                          PORTS                                                                                            NAMES
82d79b5ff88b   automuteus/automuteus:8.3.3     "./app"                  7 minutes ago    Restarting (2) 54 seconds ago                                                                                                    automuteus-automuteus-1
b0bb8aea32eb   automuteus/galactus:4.0.0       "/app/app"               13 minutes ago   Up 13 minutes                   0.0.0.0:1882->8123/tcp, :::1882->8123/tcp                                                        automuteus-galactus-1
eaed74d3e128   redis:alpine                    "docker-entrypoint.s…"   31 minutes ago   Up 29 minutes                   6379/tcp                                                                                         automuteus-redis-1
39c3c305a101   postgres:12-alpine              "docker-entrypoint.s…"   31 minutes ago   Up 29 minutes                   5432/tcp                                                                                         automuteus-postgres-1

```

**Comment by kurokobo** [comment]
@Zehir 
As a workaround, could you please add `arm_64bit=0` to your `/boot/config.txt`, and reboot RPi?
https://www.raspberrypi.com/documentation/computers/config_txt.html#arm_64bit

I think you are using 32bit version of RPi OS, but it loads 64bit kernel by default (`arm_64bit=1`). This causes your docker to pull the image for `aarch64`, and panic since the userspace is still in 32bit.

**Comment by Zehir** [comment]
`uname -m` was returning 64 bit but you may be right. I scraped everything and install rpi OS 64 bit and now it's working thanks
